
skillMetadata:
  sections:
    - name: NextCloud Calendar Credentials
      fields:
        - type: label
          label: Set your Nextcloud Calendar credentials"
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
        - name: timezone
          type: text
          label: timezone
          value: "Europe/Berlin"